[package]
name = "grin_servers"
version = "0.0.2-beta.1"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
description = "Simple, private and scalable cryptocurrency implementation based on the Mimblewimble chain format."
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/grin"
keywords = [ "crypto", "grin", "mimblewimble" ]
workspace = ".."
edition = "2018"

[dependencies]
failure = "0.1"
data-encoding = "2"
ed25519-dalek = "1"
sha3 = "0.8"
hyper = "0.13"
regex = "1.3"
sysinfo = "0.9"
dirs = "1.0.3"
timer = "0.2"
hyper-rustls = "0.20"
fs2 = "0.4"
futures = "0.3"
http = "0.2"
lmdb-zero = "0.4.4"
rand = "0.6"
serde = "1"
log = "0.4"
serde_derive = "1"
serde_json = "1"
chrono = "0.4.11"
tokio = {version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
walkdir = "2.3.1"

grin_api = { path = "../api", version = "0.0.2-beta.1" }
grin_chain = { path = "../chain", version = "0.0.2-beta.1" }
grin_core = { path = "../core", version = "0.0.2-beta.1" }
grin_keychain = { path = "../keychain", version = "0.0.2-beta.1" }
grin_p2p = { path = "../p2p", version = "0.0.2-beta.1" }
grin_pool = { path = "../pool", version = "0.0.2-beta.1" }
grin_store = { path = "../store", version = "0.0.2-beta.1" }
grin_util = { path = "../util", version = "0.0.2-beta.1" }
bmw_utxo = { path = "../utxo", version = "0.0.2-beta.1" }
